"""Official runtime contract constants for parametric control integration."""

from __future__ import annotations

DEFAULT_CONTROL_EXCHANGE = "iot_middleware"

TELEMETRY_EVENTS_ROUTING_KEY = "telemetry.events"
CONTROL_RECOMMENDATIONS_ROUTING_KEY = "control.recommendations"
SIMULATED_ACTUATION_RECOMMENDATIONS_ROUTING_KEY = "control.recommendations.simulated.v1"
CONTROL_AUDIT_ROUTING_KEY = "control.audit"

CONTROL_RECOMMENDATION_MESSAGE_TYPE = "control.recommendation"
CONTROL_AUDIT_MESSAGE_TYPE = "control.audit"

CONTROL_AUDIT_STATUS_PROCESSED = "processed"
CONTROL_AUDIT_STATUS_SKIPPED = "skipped"
CONTROL_AUDIT_STATUS_ERROR = "error"

CONTROL_AUDIT_PERSISTENCE_STATUS_NOT_ATTEMPTED = "not_attempted"
CONTROL_AUDIT_PERSISTENCE_STATUS_PENDING = "pending_best_effort"
CONTROL_AUDIT_PERSISTENCE_STATUS_PERSISTED = "persisted"
CONTROL_AUDIT_PERSISTENCE_STATUS_FAILED = "failed"

CONTROL_AUDIT_ACTION_RECOMMENDATION_EMITTED = "CONTROL_RECOMMENDATION_EMITTED"
CONTROL_AUDIT_ACTION_SKIPPED_BY_FEATURE_FLAG = "CONTROL_SKIPPED_BY_FEATURE_FLAG"
CONTROL_AUDIT_ACTION_EVALUATION_FAILED = "CONTROL_EVALUATION_FAILED"

CONTROL_SKIP_REASON_FEATURE_FLAG_DISABLED = "feature_flag_disabled"
