"""Event primitives and event bus for the Digital Twin Engine."""

from __future__ import annotations

import asyncio
import inspect
from collections import deque
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Callable, Deque, Dict, Iterable, Optional

try:  # Python 3.11+
    from enum import StrEnum
except ImportError:  # pragma: no cover
    class StrEnum(str, Enum):
        pass


class EventType(StrEnum):
    """Canonical event types supported by the engine."""

    ALERT = "ALERT"
    THRESHOLD_CROSSED = "THRESHOLD_CROSSED"
    STATE_CHANGE = "STATE_CHANGE"
    DEVICE_DISCONNECTED = "DEVICE_DISCONNECTED"


@dataclass
class TwinEvent:
    """Event generated by entities, scheduler, MQTT, or rules."""

    entity_id: str
    type: str
    payload: Dict[str, Any] = field(default_factory=dict)
    plant_id: Optional[str] = None
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> Dict[str, Any]:
        return {
            "timestamp": self.timestamp.isoformat(),
            "plant_id": self.plant_id,
            "entity_id": self.entity_id,
            "type": self.type,
            "payload": self.payload,
        }


EventCallback = Callable[[TwinEvent], Any]


@dataclass
class EventFilter:
    """Filter for selective subscription."""

    event_types: Optional[set[str]] = None
    entity_ids: Optional[set[str]] = None
    plant_ids: Optional[set[str]] = None
    predicate: Optional[Callable[[TwinEvent], bool]] = None

    def matches(self, event: TwinEvent) -> bool:
        if self.event_types and event.type not in self.event_types:
            return False
        if self.entity_ids and event.entity_id not in self.entity_ids:
            return False
        if self.plant_ids and event.plant_id not in self.plant_ids:
            return False
        if self.predicate and not self.predicate(event):
            return False
        return True


class EventBus:
    """In-memory queue + pub/sub dispatcher with optional filtering."""

    def __init__(self) -> None:
        self._queue: Deque[TwinEvent] = deque()
        self._listeners: Dict[int, tuple[EventCallback, Optional[EventFilter]]] = {}
        self._next_token = 1

    def publish(self, event: TwinEvent) -> None:
        self._queue.append(event)

    def publish_many(self, events: Iterable[TwinEvent]) -> None:
        for event in events:
            self.publish(event)

    def subscribe(self, callback: EventCallback, event_filter: Optional[EventFilter] = None) -> int:
        token = self._next_token
        self._next_token += 1
        self._listeners[token] = (callback, event_filter)
        return token

    def unsubscribe(self, token: int) -> None:
        self._listeners.pop(token, None)

    def queued(self) -> int:
        return len(self._queue)

    async def drain_async(self, max_events: Optional[int] = None) -> list[TwinEvent]:
        """Drain the queue and dispatch events to listeners (async-capable)."""
        processed: list[TwinEvent] = []
        dispatched = 0
        while self._queue and (max_events is None or dispatched < max_events):
            event = self._queue.popleft()
            processed.append(event)
            dispatched += 1
            for callback, event_filter in list(self._listeners.values()):
                if event_filter and not event_filter.matches(event):
                    continue
                result = callback(event)
                if inspect.isawaitable(result):
                    await result
        return processed

    def drain_sync(self, max_events: Optional[int] = None) -> list[TwinEvent]:
        """Drain the queue and dispatch events to listeners in sync mode."""
        processed: list[TwinEvent] = []
        dispatched = 0
        while self._queue and (max_events is None or dispatched < max_events):
            event = self._queue.popleft()
            processed.append(event)
            dispatched += 1
            for callback, event_filter in list(self._listeners.values()):
                if event_filter and not event_filter.matches(event):
                    continue
                result = callback(event)
                if inspect.isawaitable(result):
                    asyncio.run(result)
        return processed
